spring.application.name=KinoFilmai

server.port=8099

spring.datasource.url=jdbc:mysql://localhost:3306/saityno_paslaugos_filmai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

omdb.api.key=d5617581
omdb.api.url=https://www.omdbapi.com/